import {
  IconAdjustments,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowsExchange,
  IconBolt,
  IconBuilding,
  IconBuildingBank,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCalculator,
  IconCalendarEvent,
  IconCalendarStats,
  IconCash,
  IconChartBar,
  IconChartLine,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCloudCheck,
  IconCoffee,
  IconCookie,
  IconCopyOff,
  IconCup,
  IconDeviceFloppy,
  IconDownload,
  IconFileImport,
  IconFileInvoice,
  IconFilter,
  IconGift,
  IconHistory,
  IconIdBadge,
  IconIdBadge2,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconListDetails,
  IconLoader2,
  IconLock,
  IconLockAccess,
  IconLogin2,
  IconLogout,
  IconMapPin,
  IconMenu2,
  IconPackage,
  IconPaperclip,
  IconPhone,
  IconPlus,
  IconPrinter,
  IconReceipt,
  IconReceipt2,
  IconReceiptTax,
  IconRefresh,
  IconScale,
  IconSearch,
  IconSettings,
  IconShieldExclamation,
  IconShoppingCart,
  IconSum,
  IconTable,
  IconTicket,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTrophy,
  IconUnlink,
  IconUpload,
  IconUserCheck,
  IconUserOff,
  IconUserPlus,
  IconUserStar,
  IconUsers,
  IconWallet,
} from '@tabler/icons-react';

const MAP = {
  'ti-adjustments': IconAdjustments,
  'ti-alert-circle': IconAlertCircle,
  'ti-alert-triangle': IconAlertTriangle,
  'ti-arrow-left': IconArrowLeft,
  'ti-arrows-exchange': IconArrowsExchange,
  'ti-bolt': IconBolt,
  'ti-building': IconBuilding,
  'ti-building-bank': IconBuildingBank,
  'ti-building-store': IconBuildingStore,
  'ti-building-warehouse': IconBuildingWarehouse,
  'ti-calculator': IconCalculator,
  'ti-calendar-event': IconCalendarEvent,
  'ti-calendar-stats': IconCalendarStats,
  'ti-cash': IconCash,
  'ti-chart-bar': IconChartBar,
  'ti-chart-line': IconChartLine,
  'ti-check': IconCheck,
  'ti-chevron-left': IconChevronLeft,
  'ti-chevron-right': IconChevronRight,
  'ti-circle-check': IconCircleCheck,
  'ti-cloud-check': IconCloudCheck,
  'ti-coffee': IconCoffee,
  'ti-cookie': IconCookie,
  'ti-copy-off': IconCopyOff,
  'ti-cup': IconCup,
  'ti-device-floppy': IconDeviceFloppy,
  'ti-download': IconDownload,
  'ti-file-import': IconFileImport,
  'ti-file-invoice': IconFileInvoice,
  'ti-filter': IconFilter,
  'ti-gift': IconGift,
  'ti-history': IconHistory,
  'ti-id-badge': IconIdBadge,
  'ti-id-badge-2': IconIdBadge2,
  'ti-layout-dashboard': IconLayoutDashboard,
  'ti-link': IconLink,
  'ti-list': IconList,
  'ti-list-details': IconListDetails,
  'ti-loader-2': IconLoader2,
  'ti-lock': IconLock,
  'ti-lock-access': IconLockAccess,
  'ti-login-2': IconLogin2,
  'ti-logout': IconLogout,
  'ti-map-pin': IconMapPin,
  'ti-menu-2': IconMenu2,
  'ti-package': IconPackage,
  'ti-paperclip': IconPaperclip,
  'ti-phone': IconPhone,
  'ti-plus': IconPlus,
  'ti-printer': IconPrinter,
  'ti-receipt': IconReceipt,
  'ti-receipt-2': IconReceipt2,
  'ti-receipt-tax': IconReceiptTax,
  'ti-refresh': IconRefresh,
  'ti-scale': IconScale,
  'ti-search': IconSearch,
  'ti-settings': IconSettings,
  'ti-shield-alert': IconShieldExclamation,
  'ti-shopping-cart': IconShoppingCart,
  'ti-sum': IconSum,
  'ti-table': IconTable,
  'ti-ticket': IconTicket,
  'ti-trash': IconTrash,
  'ti-trending-down': IconTrendingDown,
  'ti-trending-up': IconTrendingUp,
  'ti-trophy': IconTrophy,
  'ti-unlink': IconUnlink,
  'ti-upload': IconUpload,
  'ti-user-check': IconUserCheck,
  'ti-user-off': IconUserOff,
  'ti-user-plus': IconUserPlus,
  'ti-user-star': IconUserStar,
  'ti-users': IconUsers,
  'ti-wallet': IconWallet,
};

function normalize(name) {
  if (!name) return '';
  const s = String(name).trim();
  if (s.startsWith('ti-')) return s;
  if (s.startsWith('ti ')) return `ti-${s.slice(3)}`;
  return `ti-${s}`;
}

/** Tree-shaken Tabler icon — ใช้แทน <i className="ti ti-xxx"> */
export default function Icon({ name, size = '1em', className, style, stroke = 1.75, ...rest }) {
  const Comp = MAP[normalize(name)];
  if (!Comp) return null;
  return (
    <Comp
      size={size}
      stroke={stroke}
      className={className}
      style={{ verticalAlign: '-0.125em', ...style }}
      aria-hidden
      {...rest}
    />
  );
}
